//
//  APIManager+MockJSON.swift
//  PayBayMaxChallengeTests
//
//  Created by Syed Asim Najam on 21/06/2021.
//

import Foundation
import Models

@testable import PayBayMaxChallenge

extension APIManager {
    static let liveJSON: Data = {
        let jsonString = """
{
        "success": true,
        "terms": "https://currencylayer.com/terms",
        "privacy": "https://currencylayer.com/privacy",
        "timestamp": 1624068844,
        "source": "USD",
        "quotes": {
            "USDAED": 3.673104,
            "USDAFN": 78.503991,
            "USDALL": 102.950403,
            "USDAMD": 513.730403,
            "USDANG": 1.795305,
            "USDAOA": 642.000367,
            "USDARS": 95.366118,
            "USDAUD": 1.337256,
            "USDAWG": 1.8005,
            "USDAZN": 1.70397,
            "USDBAM": 1.641658,
            "USDBBD": 2.019431,
            "USDBDT": 84.763867,
            "USDBGN": 1.650484,
            "USDBHD": 0.376928,
            "USDBIF": 1982,
            "USDBMD": 1,
            "USDBND": 1.341632,
            "USDBOB": 6.906222,
            "USDBRL": 5.09015,
            "USDBSD": 1.000189,
            "USDBTC": 2.7707302e-5,
            "USDBTN": 73.911624,
            "USDBWP": 10.830168,
            "USDBYN": 2.51407,
            "USDBYR": 19600,
            "USDBZD": 2.016074,
            "USDCAD": 1.24682,
            "USDCDF": 1984.000362,
            "USDCHF": 0.92305,
            "USDCLF": 0.02713,
            "USDCLP": 748.603912,
            "USDCNY": 6.453104,
            "USDCOP": 3769,
            "USDCRC": 617.614101,
            "USDCUC": 1,
            "USDCUP": 26.5,
            "USDCVE": 92.67504,
            "USDCZK": 21.56304,
            "USDDJF": 177.720394,
            "USDDKK": 6.268405,
            "USDDOP": 57.080393,
            "USDDZD": 134.330393,
            "USDEGP": 15.646875,
            "USDERN": 15.001999,
            "USDETB": 43.303876,
            "USDEUR": 0.842861,
            "USDFJD": 2.06504,
            "USDFKP": 0.708843,
            "USDGBP": 0.724034,
            "USDGEL": 3.16504,
            "USDGGP": 0.708843,
            "USDGHS": 5.79039,
            "USDGIP": 0.708843,
            "USDGMD": 51.15039,
            "USDGNF": 9825.000355,
            "USDGTQ": 7.736355,
            "USDGYD": 209.254013,
            "USDHKD": 7.76249,
            "USDHNL": 24.120389,
            "USDHRK": 6.32404,
            "USDHTG": 92.515014,
            "USDHUF": 299.97404,
            "USDIDR": 14489.5,
            "USDILS": 3.27836,
            "USDIMP": 0.708843,
            "USDINR": 74.144104,
            "USDIQD": 1460.5,
            "USDIRR": 42105.000352,
            "USDISK": 123.570386,
            "USDJEP": 0.708843,
            "USDJMD": 150.419889,
            "USDJOD": 0.708804,
            "USDJPY": 110.23504,
            "USDKES": 107.803804,
            "USDKGS": 84.572304,
            "USDKHR": 4075.000351,
            "USDKMF": 413.550384,
            "USDKPW": 900.00035,
            "USDKRW": 1135.250384,
            "USDKWD": 0.30135,
            "USDKYD": 0.833484,
            "USDKZT": 428.11877,
            "USDLAK": 9465.000349,
            "USDLBP": 1527.000349,
            "USDLKR": 198.782509,
            "USDLRD": 171.403775,
            "USDLSL": 14.120382,
            "USDLTL": 2.95274,
            "USDLVL": 0.60489,
            "USDLYD": 4.495039,
            "USDMAD": 8.904504,
            "USDMDL": 17.878082,
            "USDMGA": 3754.000347,
            "USDMKD": 51.717553,
            "USDMMK": 1646.26951,
            "USDMNT": 2845.998274,
            "USDMOP": 7.998338,
            "USDMRO": 356.999828,
            "USDMUR": 40.895624,
            "USDMVR": 15.450378,
            "USDMWK": 795.000345,
            "USDMXN": 20.67455,
            "USDMYR": 4.140378,
            "USDMZN": 63.010377,
            "USDNAD": 14.060377,
            "USDNGN": 410.000344,
            "USDNIO": 35.170377,
            "USDNOK": 8.670104,
            "USDNPR": 118.259001,
            "USDNZD": 1.441857,
            "USDOMR": 0.384935,
            "USDPAB": 1.000189,
            "USDPEN": 3.920375,
            "USDPGK": 3.503708,
            "USDPHP": 48.500761,
            "USDPKR": 156.850375,
            "USDPLN": 3.837504,
            "USDPYG": 6744.41931,
            "USDQAR": 3.641038,
            "USDRON": 4.153204,
            "USDRSD": 98.696884,
            "USDRUB": 72.799604,
            "USDRWF": 990,
            "USDSAR": 3.750032,
            "USDSBD": 7.996864,
            "USDSCR": 15.496003,
            "USDSDG": 437.503678,
            "USDSEK": 8.60911,
            "USDSGD": 1.344735,
            "USDSHP": 0.708843,
            "USDSLL": 10235.000339,
            "USDSOS": 585.000338,
            "USDSRD": 21.415504,
            "USDSTD": 20408.496127,
            "USDSVC": 8.752072,
            "USDSYP": 1257.841696,
            "USDSZL": 14.12037,
            "USDTHB": 31.444038,
            "USDTJS": 11.406988,
            "USDTMT": 3.51,
            "USDTND": 2.766504,
            "USDTOP": 2.24795,
            "USDTRY": 8.741904,
            "USDTTD": 6.788878,
            "USDTWD": 27.794504,
            "USDTZS": 2319.000336,
            "USDUAH": 27.197398,
            "USDUGX": 3535.578638,
            "USDUSD": 1,
            "USDUYU": 43.681933,
            "USDUZS": 10600.000335,
            "USDVEF": 213830222338.07285,
            "USDVND": 23000,
            "USDVUV": 108.440804,
            "USDWST": 2.521973,
            "USDXAF": 550.583565,
            "USDXAG": 0.038748,
            "USDXAU": 0.000567,
            "USDXCD": 2.70255,
            "USDXDR": 0.699774,
            "USDXOF": 548.503602,
            "USDXPF": 100.350364,
            "USDYER": 250.050364,
            "USDZAR": 14.35261,
            "USDZMK": 9001.203593,
            "USDZMW": 22.583905,
            "USDZWL": 322.000331
        }
    }
"""
       return jsonString.data(using: .utf8)!
        
    }()
    
    static let listJSON: Data = {
        let jsonString = """
        {
            "success": true,
            "terms": "https://currencylayer.com/terms",
            "privacy": "https://currencylayer.com/privacy",
            "currencies": {
                "AED": "United Arab Emirates Dirham",
                "AFN": "Afghan Afghani",
                "ALL": "Albanian Lek",
                "AMD": "Armenian Dram",
                "ANG": "Netherlands Antillean Guilder",
                "AOA": "Angolan Kwanza",
                "ARS": "Argentine Peso",
                "AUD": "Australian Dollar",
                "AWG": "Aruban Florin",
                "AZN": "Azerbaijani Manat",
                "BAM": "Bosnia-Herzegovina Convertible Mark",
                "BBD": "Barbadian Dollar",
                "BDT": "Bangladeshi Taka",
                "BGN": "Bulgarian Lev",
                "BHD": "Bahraini Dinar",
                "BIF": "Burundian Franc",
                "BMD": "Bermudan Dollar",
                "BND": "Brunei Dollar",
                "BOB": "Bolivian Boliviano",
                "BRL": "Brazilian Real",
                "BSD": "Bahamian Dollar",
                "BTC": "Bitcoin",
                "BTN": "Bhutanese Ngultrum",
                "BWP": "Botswanan Pula",
                "BYN": "New Belarusian Ruble",
                "BYR": "Belarusian Ruble",
                "BZD": "Belize Dollar",
                "CAD": "Canadian Dollar",
                "CDF": "Congolese Franc",
                "CHF": "Swiss Franc",
                "CLF": "Chilean Unit of Account (UF)",
                "CLP": "Chilean Peso",
                "CNY": "Chinese Yuan",
                "COP": "Colombian Peso",
                "CRC": "Costa Rican Colón",
                "CUC": "Cuban Convertible Peso",
                "CUP": "Cuban Peso",
                "CVE": "Cape Verdean Escudo",
                "CZK": "Czech Republic Koruna",
                "DJF": "Djiboutian Franc",
                "DKK": "Danish Krone",
                "DOP": "Dominican Peso",
                "DZD": "Algerian Dinar",
                "EGP": "Egyptian Pound",
                "ERN": "Eritrean Nakfa",
                "ETB": "Ethiopian Birr",
                "EUR": "Euro",
                "FJD": "Fijian Dollar",
                "FKP": "Falkland Islands Pound",
                "GBP": "British Pound Sterling",
                "GEL": "Georgian Lari",
                "GGP": "Guernsey Pound",
                "GHS": "Ghanaian Cedi",
                "GIP": "Gibraltar Pound",
                "GMD": "Gambian Dalasi",
                "GNF": "Guinean Franc",
                "GTQ": "Guatemalan Quetzal",
                "GYD": "Guyanaese Dollar",
                "HKD": "Hong Kong Dollar",
                "HNL": "Honduran Lempira",
                "HRK": "Croatian Kuna",
                "HTG": "Haitian Gourde",
                "HUF": "Hungarian Forint",
                "IDR": "Indonesian Rupiah",
                "ILS": "Israeli New Sheqel",
                "IMP": "Manx pound",
                "INR": "Indian Rupee",
                "IQD": "Iraqi Dinar",
                "IRR": "Iranian Rial",
                "ISK": "Icelandic Króna",
                "JEP": "Jersey Pound",
                "JMD": "Jamaican Dollar",
                "JOD": "Jordanian Dinar",
                "JPY": "Japanese Yen",
                "KES": "Kenyan Shilling",
                "KGS": "Kyrgystani Som",
                "KHR": "Cambodian Riel",
                "KMF": "Comorian Franc",
                "KPW": "North Korean Won",
                "KRW": "South Korean Won",
                "KWD": "Kuwaiti Dinar",
                "KYD": "Cayman Islands Dollar",
                "KZT": "Kazakhstani Tenge",
                "LAK": "Laotian Kip",
                "LBP": "Lebanese Pound",
                "LKR": "Sri Lankan Rupee",
                "LRD": "Liberian Dollar",
                "LSL": "Lesotho Loti",
                "LTL": "Lithuanian Litas",
                "LVL": "Latvian Lats",
                "LYD": "Libyan Dinar",
                "MAD": "Moroccan Dirham",
                "MDL": "Moldovan Leu",
                "MGA": "Malagasy Ariary",
                "MKD": "Macedonian Denar",
                "MMK": "Myanma Kyat",
                "MNT": "Mongolian Tugrik",
                "MOP": "Macanese Pataca",
                "MRO": "Mauritanian Ouguiya",
                "MUR": "Mauritian Rupee",
                "MVR": "Maldivian Rufiyaa",
                "MWK": "Malawian Kwacha",
                "MXN": "Mexican Peso",
                "MYR": "Malaysian Ringgit",
                "MZN": "Mozambican Metical",
                "NAD": "Namibian Dollar",
                "NGN": "Nigerian Naira",
                "NIO": "Nicaraguan Córdoba",
                "NOK": "Norwegian Krone",
                "NPR": "Nepalese Rupee",
                "NZD": "New Zealand Dollar",
                "OMR": "Omani Rial",
                "PAB": "Panamanian Balboa",
                "PEN": "Peruvian Nuevo Sol",
                "PGK": "Papua New Guinean Kina",
                "PHP": "Philippine Peso",
                "PKR": "Pakistani Rupee",
                "PLN": "Polish Zloty",
                "PYG": "Paraguayan Guarani",
                "QAR": "Qatari Rial",
                "RON": "Romanian Leu",
                "RSD": "Serbian Dinar",
                "RUB": "Russian Ruble",
                "RWF": "Rwandan Franc",
                "SAR": "Saudi Riyal",
                "SBD": "Solomon Islands Dollar",
                "SCR": "Seychellois Rupee",
                "SDG": "Sudanese Pound",
                "SEK": "Swedish Krona",
                "SGD": "Singapore Dollar",
                "SHP": "Saint Helena Pound",
                "SLL": "Sierra Leonean Leone",
                "SOS": "Somali Shilling",
                "SRD": "Surinamese Dollar",
                "STD": "São Tomé and Príncipe Dobra",
                "SVC": "Salvadoran Colón",
                "SYP": "Syrian Pound",
                "SZL": "Swazi Lilangeni",
                "THB": "Thai Baht",
                "TJS": "Tajikistani Somoni",
                "TMT": "Turkmenistani Manat",
                "TND": "Tunisian Dinar",
                "TOP": "Tongan Paʻanga",
                "TRY": "Turkish Lira",
                "TTD": "Trinidad and Tobago Dollar",
                "TWD": "New Taiwan Dollar",
                "TZS": "Tanzanian Shilling",
                "UAH": "Ukrainian Hryvnia",
                "UGX": "Ugandan Shilling",
                "USD": "United States Dollar",
                "UYU": "Uruguayan Peso",
                "UZS": "Uzbekistan Som",
                "VEF": "Venezuelan Bolívar Fuerte",
                "VND": "Vietnamese Dong",
                "VUV": "Vanuatu Vatu",
                "WST": "Samoan Tala",
                "XAF": "CFA Franc BEAC",
                "XAG": "Silver (troy ounce)",
                "XAU": "Gold (troy ounce)",
                "XCD": "East Caribbean Dollar",
                "XDR": "Special Drawing Rights",
                "XOF": "CFA Franc BCEAO",
                "XPF": "CFP Franc",
                "YER": "Yemeni Rial",
                "ZAR": "South African Rand",
                "ZMK": "Zambian Kwacha (pre-2013)",
                "ZMW": "Zambian Kwacha",
                "ZWL": "Zimbabwean Dollar"
            }
        }
        """
        return jsonString.data(using: .utf8)!
    }()
}
